services:
  master:
    image: hadoop-master
    container_name: master
    hostname: master
    ports:
      - "9870:9870"
      - "8088:8088"
    volumes:
      - ./data/namenode:/hadoop/dfs/name
    networks:
      - hadoop-net

  worker1:
    image: hadoop-worker
    container_name: worker1
    hostname: worker1
    volumes:
      - ./data/datanode:/hadoop/dfs/data
    networks:
      - hadoop-net

  worker2:
    image: hadoop-worker
    container_name: worker2
    hostname: worker2
    volumes:
      - ./data/datanode:/hadoop/dfs/data
    networks:
      - hadoop-net

networks:
  hadoop-net: