services:
  master:
    image: hadoop-master
    container_name: master
    hostname: namenode
    ports:
      - "9870:9870"
      - "8088:8088"
    volumes:
      - ./config/core-site.xml:/opt/hadoop/etc/hadoop/core-site.xml
      - ./config/hdfs-site.xml:/opt/hadoop/etc/hadoop/hdfs-site.xml
      - ./config/yarn-site.xml:/opt/hadoop/etc/hadoop/yarn-site.xml
      - ./config/mapred-site.xml:/opt/hadoop/etc/hadoop/mapred-site.xml
      - ./config/workers:/opt/hadoop/etc/hadoop/workers
      - ./data/namenode:/hadoop/dfs/name
    networks:
      - hadoop-net

  worker1:
    image: hadoop-worker
    container_name: worker1
    hostname: worker1
    volumes:
      - ./config/core-site.xml:/opt/hadoop/etc/hadoop/core-site.xml
      - ./config/hdfs-site.xml:/opt/hadoop/etc/hadoop/hdfs-site.xml
      - ./config/yarn-site.xml:/opt/hadoop/etc/hadoop/yarn-site.xml
      - ./config/mapred-site.xml:/opt/hadoop/etc/hadoop/mapred-site.xml
      - ./config/workers:/opt/hadoop/etc/hadoop/workers
      - ./data/datanode1:/hadoop/dfs/data
    networks:
      - hadoop-net

  worker2:
    image: hadoop-worker
    container_name: worker2
    hostname: worker2
    volumes:
      - ./config/core-site.xml:/opt/hadoop/etc/hadoop/core-site.xml
      - ./config/hdfs-site.xml:/opt/hadoop/etc/hadoop/hdfs-site.xml
      - ./config/yarn-site.xml:/opt/hadoop/etc/hadoop/yarn-site.xml
      - ./config/mapred-site.xml:/opt/hadoop/etc/hadoop/mapred-site.xml
      - ./config/workers:/opt/hadoop/etc/hadoop/workers
      - ./data/datanode2:/hadoop/dfs/data
    networks:
      - hadoop-net

networks:
  hadoop-net: