services:
  master:
    image: hadoop-master
    container_name: master
    hostname: master
    mem_limit: 4g
    ports:
      - "9870:9870"
      - "8088:8088"
    volumes:
      - ./config/core-site.xml:/opt/hadoop/etc/hadoop/core-site.xml
      - ./config/hdfs-site.xml:/opt/hadoop/etc/hadoop/hdfs-site.xml
      - ./config/yarn-site.xml:/opt/hadoop/etc/hadoop/yarn-site.xml
      - ./config/mapred-site.xml:/opt/hadoop/etc/hadoop/mapred-site.xml
      - ./config/workers:/opt/hadoop/etc/hadoop/workers
      - ./data/namenode:/hadoop/dfs/name
      - ./data/amazon:/data/amazon
      - ./src:/src
    networks:
      - hadoop-net

  worker1:
    image: hadoop-worker
    container_name: worker1
    hostname: worker1
    mem_limit: 2g
    volumes:
      - ./config/core-site.xml:/opt/hadoop/etc/hadoop/core-site.xml
      - ./config/hdfs-site.xml:/opt/hadoop/etc/hadoop/hdfs-site.xml
      - ./config/yarn-site.xml:/opt/hadoop/etc/hadoop/yarn-site.xml
      - ./config/mapred-site.xml:/opt/hadoop/etc/hadoop/mapred-site.xml
      - ./config/workers:/opt/hadoop/etc/hadoop/workers
      - ./data/datanode1:/hadoop/dfs/data
    networks:
      - hadoop-net

  worker2:
    image: hadoop-worker
    container_name: worker2
    hostname: worker2
    mem_limit: 2g
    volumes:
      - ./config/core-site.xml:/opt/hadoop/etc/hadoop/core-site.xml
      - ./config/hdfs-site.xml:/opt/hadoop/etc/hadoop/hdfs-site.xml
      - ./config/yarn-site.xml:/opt/hadoop/etc/hadoop/yarn-site.xml
      - ./config/mapred-site.xml:/opt/hadoop/etc/hadoop/mapred-site.xml
      - ./config/workers:/opt/hadoop/etc/hadoop/workers
      - ./data/datanode2:/hadoop/dfs/data
    networks:
      - hadoop-net

  worker3:
    image: hadoop-worker
    container_name: worker3
    hostname: worker3
    mem_limit: 2g
    volumes:
      - ./config/core-site.xml:/opt/hadoop/etc/hadoop/core-site.xml
      - ./config/hdfs-site.xml:/opt/hadoop/etc/hadoop/hdfs-site.xml
      - ./config/yarn-site.xml:/opt/hadoop/etc/hadoop/yarn-site.xml
      - ./config/mapred-site.xml:/opt/hadoop/etc/hadoop/mapred-site.xml
      - ./config/workers:/opt/hadoop/etc/hadoop/workers
      - ./data/datanode3:/hadoop/dfs/data
    networks:
      - hadoop-net

  worker4:
    image: hadoop-worker
    container_name: worker4
    hostname: worker4
    mem_limit: 2g
    volumes:
      - ./config/core-site.xml:/opt/hadoop/etc/hadoop/core-site.xml
      - ./config/hdfs-site.xml:/opt/hadoop/etc/hadoop/hdfs-site.xml
      - ./config/yarn-site.xml:/opt/hadoop/etc/hadoop/yarn-site.xml
      - ./config/mapred-site.xml:/opt/hadoop/etc/hadoop/mapred-site.xml
      - ./config/workers:/opt/hadoop/etc/hadoop/workers
      - ./data/datanode4:/hadoop/dfs/data
    networks:
      - hadoop-net

  worker5:
    image: hadoop-worker
    container_name: worker5
    hostname: worker5
    mem_limit: 2g
    volumes:
      - ./config/core-site.xml:/opt/hadoop/etc/hadoop/core-site.xml
      - ./config/hdfs-site.xml:/opt/hadoop/etc/hadoop/hdfs-site.xml
      - ./config/yarn-site.xml:/opt/hadoop/etc/hadoop/yarn-site.xml
      - ./config/mapred-site.xml:/opt/hadoop/etc/hadoop/mapred-site.xml
      - ./config/workers:/opt/hadoop/etc/hadoop/workers
      - ./data/datanode5:/hadoop/dfs/data
    networks:
      - hadoop-net

  worker6:
    image: hadoop-worker
    container_name: worker6
    hostname: worker6
    mem_limit: 2g
    volumes:
      - ./config/core-site.xml:/opt/hadoop/etc/hadoop/core-site.xml
      - ./config/hdfs-site.xml:/opt/hadoop/etc/hadoop/hdfs-site.xml
      - ./config/yarn-site.xml:/opt/hadoop/etc/hadoop/yarn-site.xml
      - ./config/mapred-site.xml:/opt/hadoop/etc/hadoop/mapred-site.xml
      - ./config/workers:/opt/hadoop/etc/hadoop/workers
      - ./data/datanode6:/hadoop/dfs/data
    networks:
      - hadoop-net

  worker7:
    image: hadoop-worker
    container_name: worker7
    hostname: worker7
    mem_limit: 2g
    volumes:
      - ./config/core-site.xml:/opt/hadoop/etc/hadoop/core-site.xml
      - ./config/hdfs-site.xml:/opt/hadoop/etc/hadoop/hdfs-site.xml
      - ./config/yarn-site.xml:/opt/hadoop/etc/hadoop/yarn-site.xml
      - ./config/mapred-site.xml:/opt/hadoop/etc/hadoop/mapred-site.xml
      - ./config/workers:/opt/hadoop/etc/hadoop/workers
      - ./data/datanode7:/hadoop/dfs/data
    networks:
      - hadoop-net

  worker8:
    image: hadoop-worker
    container_name: worker8
    hostname: worker8
    mem_limit: 2g
    volumes:
      - ./config/core-site.xml:/opt/hadoop/etc/hadoop/core-site.xml
      - ./config/hdfs-site.xml:/opt/hadoop/etc/hadoop/hdfs-site.xml
      - ./config/yarn-site.xml:/opt/hadoop/etc/hadoop/yarn-site.xml
      - ./config/mapred-site.xml:/opt/hadoop/etc/hadoop/mapred-site.xml
      - ./config/workers:/opt/hadoop/etc/hadoop/workers
      - ./data/datanode8:/hadoop/dfs/data
    networks:
      - hadoop-net

  worker9:
    image: hadoop-worker
    container_name: worker9
    hostname: worker9
    mem_limit: 2g
    volumes:
      - ./config/core-site.xml:/opt/hadoop/etc/hadoop/core-site.xml
      - ./config/hdfs-site.xml:/opt/hadoop/etc/hadoop/hdfs-site.xml
      - ./config/yarn-site.xml:/opt/hadoop/etc/hadoop/yarn-site.xml
      - ./config/mapred-site.xml:/opt/hadoop/etc/hadoop/mapred-site.xml
      - ./config/workers:/opt/hadoop/etc/hadoop/workers
      - ./data/datanode9:/hadoop/dfs/data
    networks:
      - hadoop-net

  worker10:
    image: hadoop-worker
    container_name: worker10
    hostname: worker10
    mem_limit: 2g
    volumes:
      - ./config/core-site.xml:/opt/hadoop/etc/hadoop/core-site.xml
      - ./config/hdfs-site.xml:/opt/hadoop/etc/hadoop/hdfs-site.xml
      - ./config/yarn-site.xml:/opt/hadoop/etc/hadoop/yarn-site.xml
      - ./config/mapred-site.xml:/opt/hadoop/etc/hadoop/mapred-site.xml
      - ./config/workers:/opt/hadoop/etc/hadoop/workers
      - ./data/datanode10:/hadoop/dfs/data
    networks:
      - hadoop-net

  worker11:
    image: hadoop-worker
    container_name: worker11
    hostname: worker11
    mem_limit: 2g
    volumes:
      - ./config/core-site.xml:/opt/hadoop/etc/hadoop/core-site.xml
      - ./config/hdfs-site.xml:/opt/hadoop/etc/hadoop/hdfs-site.xml
      - ./config/yarn-site.xml:/opt/hadoop/etc/hadoop/yarn-site.xml
      - ./config/mapred-site.xml:/opt/hadoop/etc/hadoop/mapred-site.xml
      - ./config/workers:/opt/hadoop/etc/hadoop/workers
      - ./data/datanode11:/hadoop/dfs/data
    networks:
      - hadoop-net

networks:
  hadoop-net: