font_path: "/System/Library/Fonts/AppleGothic.ttf"
data_path: "../../data/raw/blind_posts.csv"
encoding: "utf-8-sig"
custom_stop_words: {'거', '것', '사람', '생각', '결혼', '상견례', '추천', '남친', '식당', '남편', '결정', '듯', '부모', '부모님', '형', '어머니', '엄마', '집', '감사', '너', '정도', '분', 돈', '말', '때문', '앞', '삭제', '로켓프레시', '여자', '남자', '본인', '마음', '그거', '고민', '년', '친구', '데', '곳', '그거', '작성자', '댓글', '쪽', '아빠', '이겨', '글', '명', '점', '문제', '중요', '만 원', '언니', '필요', '중', '전', '이거', '신경', '아버지', '원', '이해', '선택', '가족', '여친', '누구', '상황', '집안', '거기', '터', '가능', '외모', '조건', '만', '와이프', '인'}
figure_width: 800
figure_height: 400
figure_background: 'white'
figure_title: 'Word Cloud From Blind'